### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by MythicalPlatypus** [azusa0127/eslint-config-standard-next#1]
Just leaving this here because my ESLint told me!
`[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard-next")`

node --version => v10.11.0
npm -v => 6.4.1

**Comment by azusa0127** [comment]
Thanks for noticing, will remove that in the next patch version today!

**Comment by azusa0127** [comment]
Version 12.0.0 is released :), let me know if that warning still present.
